<!-- PUT THE TEXT HERE -->
<!-- BEGIN -->

THIS SITE IS CURRENTLY UNDER CONSTRUCTION!<br><br>
IT'S DEDICATED TO A FREE SOFTWARE PROJECT UNDER <a href="license.html">GNU GPL LICENSE</a> FOR FAST AND COMPLETE DYNCAMIC WEB SITES DEVELOPMENT<br><br>
TO SUPPORT MULTI-PLATFORM DEVELOPMENT THE CLIENT SIDE OF THE PROJECT IS BASED ON THE CLX LIBRARY MADE AVAILABLE TRHOUGH THE USE OF DELPHI FOR WINDOWS AND KYLIX FOR LINUX. THE SERVER SIDE OF THE PROJECT IS PHP
<br><br>
FEEL FREE TO <a href="mailto:davidbl@wanadoo.fr">CONTACT ME</a> IF YOU'RE INTERESTED IN THIS PROJECT.
<!-- END -->
