			<UL>
				The Leela project has 2 objectives: On the one hand, to create a development environment which will help conceiving dynamic web sites and on the other hand, to propose a whole set of components giving the possibility of developing other applications based on the same model.<p>

			<b>1 - The Leela Application</b><p>

				The development of this software began two years ago. At that time, I didn't know which direction to take exactly. Several bits of applications coexisted from each other independently. One was devoted to graphics, another to text processing and the third one was to generate reports/ratios using databases. Later the whole application was gathered in one with a global interface. This project being purely "voluntary" its progression was slowed down by the time devoted to work, the holidays and the festivals ;^) After acquiring more knowledge in web programming, the project took the direction it has today.<br>
			Leela is a three thirds Client/Server application requiring the installation of an operating system (Windows or Linux),a Web server (Apache) supporting a scripting language (PHP) and a database server (MySQL). By reconsidering the way the project was being developed, it appeared necessary to develop components that would facilitate the software programming.<p>

			<b>2 - The TPHP components</b><p>

				Since this architecture is generally necessary to produce a dynamic web site, I decided to place at the disposal the resources and competences needed to set up such a platform, for the creation of other applications using databases. This is made possible by creating client-side components. These components implement several technologies. They are written using the <a href="http://www.borland.fr/Presse/2000/cmq_clx.asp">CLX</a> library for the environments <a href="http://www.borland.fr/produits/delphi">Delphi</a> and <a href="http://www.borland.fr/produits/kylix">Kylix</a> in order to ensure a maximum of compatibility between the platforms Windows and Linux. It draw mainly part of the resources from the <a href="http://www.php.net">PHP</a>, thus they are gathered under the banner TPHP. The PHP scripts created for the circumstance call upon databases and for the moment, only MySQL is supported.<br>
				In addition to the facility of programming and the fact that these components are reusable, those main goal is to offer the possibility to be totally independent from a web browser when showing data generated by PHP scripts: The data appears in a more flexible traditional graphic interface with a more professional aspect.<p>
			</UL>

