#!/bin/bash
pwd

echo > logs/debug.log
echo > web/php_error_log
find runtime -type f -exec echo {} \; 
find runtime -type f -exec rm -f {} \; 
find web/js/runtime -type f -exec echo {} \; 
find web/js/runtime -type f -exec rm -f {} \; 
echo "All logs and temporary files cleared at "$(date) 
