<!-- PUT THE TEXT HERE -->
<!-- BEGIN -->

CE SITE EST ACTUELLEMENT EN CONSTRUCTION!<br><br>
IL EST DEDIE A UN PROJET DE LOGICIEL LIBRE SOUS LICENCE <a href="license.html">GNU GPL</a> POUR LE DEVELOPPEMENT RAPIDE ET COMPLET DE SITES WEBS DYNAMIQUES<br><br>
A DES FINS DE PORTABILITE ACCRUE CE PROJET EST BASE SUR DES OUTILS ET TECHNOLOGIES OUVERTS ET RECENTS COMME DELPHI/KYLIX ET PHP.<br><br>
SI CE PROJET VOUS INTERESSE, <a href="mailto:davidbl@wanadoo.fr">CONTACTEZ MOI.</a>
<!-- END -->
