	Le projet Puzzle a globalement 2 objectifs, d'une part créer un envrionnement de développement pour concevoir des sites web dynamiques et d'autre part proposer un ensemble de composants donnant la possibilité de développer d'autres applications sur le même modèle.<p>

	<b>1 - L'Application Puzzle</b><p>

	Le développement de ce logiciel a débuté il y a deux ans. A l'époque je ne savais pas exactement quelle direction prendre. Plusieurs bribes d'applications coexistaient indépendament les unes des autres. L'une était consacrée au graphisme, une autre était un mini traitement de textes et la troisième devait générer des rapports utilisant des bases de données. Plus tard l'ensemble des applications a été rassemblé dans une seule et même interface. Après réflexion et quelques connaissances en plus dans la programmation notament orientée vers le web, le projet a pris la direction qu'il connaît aujourd'hui.<br>
	Puzzle est une application CLient/Server trois tiers nécessitant la mise en place d'un système client (Windows ou Linux), d'un serveur web (Apache) doté d'un langage de script (PHP) et d'un serveur de base de données (MySQL). En repensant la mannière de développer le projet, il m'est apparu nécessaire de développer des composants pour faciliter la programmation du logiciel.<p>

	<b>2 - Les composants Pieces Of Puzzle (P.O.P)</b><p>

	Puisque l'architecture Client Web/Serveur Web/Serveur SQL est généralement nécessaire pour produire un site web dynamique, il m'est venu à l'idée de mettre à disposition les ressources et compétences de ce type de plate-forme pour la création d'autres applications tirant partie des bases de données. C'est en créant des composants côté client que cela est rendu possible. Ces composants mettent en oeuvre plusieurs technologies. Il sont écrits en utilisant la bibliothèque CLX (Component Livrary for Cross-platform) pour les environnements <a href="http://www.borland.fr/delphi" target="_new">Delphi</a> et <a href="http://www.borland.fr/kylix" target="_new">Kylix</a> de Borland afin d'assurer un maximum de compatibilité entre les plate-formes Windows et Linux. Il tirent principalement partie des ressources du <a href="http://www.php.net">PHP</a> et sont rassemblés sous la bannière Pieces Of Puzzle. Les scripts PHP crées pour la circonstance font appel aux bases de données, pour l'instant seul <a href="http://www.mysql.com" target="_new">MySQL</a> est supporté.<br>
	Outre la facilité de propgrammation et la réutilisation qui sont des caractéristiques communes à tous composants, ceux-ci ont pour rôle principal de proposer aux développeurs de ne plus dépendre du navigateur web pour afficher des données traitées par des scripts PHP. Les données apparaissent dans une interface graphique traditionnelle donnant plus de souplesse d'utilisation ainsi qu'un aspect plus professionnel aux applications internet/intranet.<p> 
