<!DOCTYPE html>
<html lang="en" debug="true" >
    <head>
        <meta http-equiv="content-type" content="text/html; charset=UTF-8">
        <meta charset="utf-8">
        <title>Puzzle Factory</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

        <meta name="description" content="">
        <meta name="author" content="">

        <link href="css/_3rdparty.css" rel="stylesheet">
        <link href="css/full-slider.css" rel="stylesheet">


        <script type="text/javascript" 
                data-depends="js/_3rdparty.js;
                    js/webfactory.js" 
                src="/phink.js">
        </script>
    </head>
    <body data-twttr-rendered="true" data-spy="scroll" >
        <div id='body'></div>


    </body>
</html>