<body bgcolor="<?php echo $this->back_color?>" text="<?php echo $this->text_color?>" link="<?php echo $this->link_color?>" vlink="<?php echo $this->vlink_color?>" alink="<?php echo $this->alink_color?>" leftmargin="0" topmargin="0">

<center>
  <table id="my_table_shadow" border="0" cellspacing="0" cellpadding="0">
    <tr><td bgcolor="white" height="3" colspan="2"></td></tr>
    <tr>
      <td rowspan="2" colspan="2">

<table border="1" cellpadding="0" cellspacing="0" height="760" width="760" valign="top"><tr><td>
<table id="my_table" bgcolor="white" border="0" cellpadding="0" cellspacing="0" height="100%" width="100%">
	<tr height="80">
		<td width="250" height="80" align="left" valign="top" style="font-size: 14;">
			<img id="logo"
	  			src="<?php echo $this->img?>/small_logo.png"
				onMouseOut="PZ_IMG.src='<?php echo $this->img?>/small_logo.png';"
				onMouseOver="PZ_IMG=document.getElementById('logo');
						PZ_IMG.src='<?php echo $this->img?>/small_logo_light.png';"
			  	onClick="document.location.href='<?php echo "."?>'"
	  		>
		</td>
		<td style="font-size: 30" width="510" height="80" align="right" valign="middle">
			<!--img src="<?php echo $this->img?>/admin/<?php echo $this->di?>.png" valign="top" border="0"-->
			<?php echo $this->title?>
			&nbsp;
		</td>
	</tr>
	<tr>
		<td colspan="2" bgcolor="black" height="8" align="center" valign="top">
		<?php echo $this->toplinks;?>
		</td>
	</tr>
	<tr>
		<td colspan="2" bgcolor="black" height="1" align="center" valign="top"></td>
	</tr>
	<tr bgcolor="#a8eaff">
		<td colspan="2" align="left" valign="top" height="680">
		<?php
			//include($this->page);
		?>
		</td>
	</tr>
</table>
</td></tr></table>

      </td>
      <td background="<?php echo $this->img?>/shadows/top_right.png" style="font-size: 1; width:11; height:8;"></td>
    </tr>
    <tr>
      <td id="my_table_sh" background="<?php echo $this->img?>/shadows/right.png" style="font-size: 1; width:11;"></td>
    </tr>
    <tr>
      <td background="<?php echo $this->img?>/shadows/bottom_left.png" style="font-size: 1; width:8; height:11;"></td>
      <td id="my_table_sw" background="<?php echo $this->img?>/shadows/bottom.png" style="font-size: 1; height: 11"></td>
      <td background="<?php echo $this->img?>/shadows/bottom_right.png" style="font-size: 1; width:11; height:11;"></td>
    </tr>
  </table>
</center>
<script language="JavaScript">
	pz_shadow("my_table");

<?php 
	echo $_SESSION["javascript"];
?>
</script>
</body>